### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by nikic** [php/php-langspec#185]
Test body

**Comment by Hywan** [comment]
Do you need a reply for your test ;-)?

**Comment by nikic** [comment]
It looks like I broke the tool for sending PR mails to the ML... Not sure what's wrong, it seems to work locally.

**Comment by nikic** [comment]
Another test.

**Comment by nikic** [comment]
Yay, it works. Wasn't my fault after all, just the mail server being broken the last two weeks.
