### ISSUE TITLE
`instanceof-subject` and `instanceof-type-designator` cannot be `expression`

### ISSUE THREAD

**Issue by Hywan** [php/php-langspec#202]
If I read the grammar correctly, [`instanceof`](https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#instanceof-operator) is defined as follow:

```
instanceof-expression:
   unary-expression
   instanceof-subject   instanceof   instanceof-type-designator

instanceof-subject:
   expression

instanceof-type-designator:
   qualified-name
   expression
```

But [`expression`](https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#grammar-expression) is defined as:

```
expression:
   yield-expression
   include-expression
   include-once-expression
   require-expression
   require-once-expression
```

So it does not make sense. Maybe instace of `expression` we should use `primary-expression` (but even not really) or `assignment` (or thinner):

```diff
  instanceof-subject:
-    expression
+    assignment

  instanceof-type-designator:
     qualified-name
-    expression
+    assignement
```

Thoughts?

**Comment by nikic** [comment]
There is not `assignment` production, did you mean `variable`? That would be better than what we have right now, though it's not entirely correct. The RHS of instanceof is a "new variable", which is a slightly restricted form of "variable", which is currently not the grammar :/

**Comment by mattacosta** [comment]
If I remember the grammar correctly, "new variable" was actually very restricted. To the point where it is basically just something like:

```
instanceof-type-designator:
  simple-variable
  qualified-name :: simple-variable
  instanceof-type-designator [ expression<sub>opt</sub> ]
  instanceof-type-designator { expression }
  instanceof-type-designator -> member-name
  instanceof-type-designator :: simple-variable
```

**Comment by Hywan** [comment]
It sounds a little bit complicated… The PHP grammar has so much different nodes…
