### ISSUE TITLE
Trait insteadof clause should accept a list of trait names instead of a single name

### ISSUE THREAD

**Issue by TysonAndre** [php/php-langspec#217]
The below code is syntactically valid, and needed to indicate which implementation of `foo` to inherit

```
<?php 
class C{
    use T1,T2,T3{T1::foo insteadof T2,T3;}
}
```

Currently, the specification says that it accepts a single name. https://github.com/php/php-langspec/blob/master/spec/16-traits.md#trait-uses

<pre>
<i id="grammar-trait-select-insteadof-clause">trait-select-insteadof-clause:</i>
   <i><a href="09-lexical-structure.md#grammar-name">name</a></i>   insteadof   <i><a href="09-lexical-structure.md#grammar-name">name</a></i>
</pre>
Should that be `  name 'insteadof' trait-name-list`? Also, I'm not familiar with this project or why it's `name` instead of `qualified-name`

Noticed when working on https://github.com/Microsoft/tolerant-php-parser/issues/190

**Comment by nikic** [comment]
The RHS should indeed be `trait-name-list`. The LHS should be `qualified-name '::' name`. Would you like to submit a PR?

**Comment by TysonAndre** [comment]
I created https://github.com/php/php-langspec/pull/218 for this
