### ISSUE TITLE
isset variable list may include trialing ','

### ISSUE THREAD

**Issue by zhujinxuan** [php/php-langspec#228]
In php 7.3.0, isset is legal for the following code:
```
isset($a,);
```
<img width="200" alt="screenshot 2018-12-20 17 00 06" src="https://user-images.githubusercontent.com/746159/50313254-b7568c80-0478-11e9-9709-d3cefa242406.png">

However, the isset variable list is defined by 
```
isset-intrinsic:
   isset   (   variable-list   )

variable-list:
   variable
   variable-list   ,   variable
```
in `10-expression.md`. 

If we plan to make the spec consistent with current PHP, I can submit a PR to change it as 
```
isset-intrinsic:
   isset   (   isset-variable-list  ','? )

variable-list:
   variable
   variable-list   ,   variable
```

**Comment by nikic** [comment]
> If we plan to make the spec consistent with current PHP, I can submit a PR to change it as

Looks right, please do so :)

**Comment by zhujinxuan** [comment]
@nikic Thank you.  Submitted in #229 .  Do we need to change tests for the `isset` behavior?

**Comment by zhujinxuan** [comment]
Merged, Close this issue
