### ISSUE TITLE
Misleading conversion float to int

### ISSUE THREAD

**Issue by Tomanhez** [php/php-langspec#242]
![Screenshot 2019-09-25 at 16 10 00](https://user-images.githubusercontent.com/39232096/65609038-68adc400-dfaf-11e9-9d5f-5bd37d3dc6b4.png)

If you have float var where decimal variable is 05, like this: 33.05 and multiply it by 100 
You mistakenly get 3305 but if convert it on int you have 3304

Certainly occurs in php 7.1.25 - 7.4.0

**Comment by nikic** [comment]
32.05*100 is 3204.9999999999995 due to limited float precision, which is 3204 when rounding down, which is what (int) does (for positive numbers). Use `round()` is you want to round.
