### ISSUE TITLE
Confused by `clone-expression` definition

### ISSUE THREAD

**Issue by ramsey** [php/php-langspec#261]
The `clone-expression` is defined as:

```
clone-expression:
   primary-expression
   clone   primary-expression
```

I don't understand how to read this. A `clone-expression` can be `primary-expression` *or* `'clone' primary-expression`?

Is this a mistake? Should it be the following instead (note the use of recursively using `clone-expression`)?

```
clone-expression:
   primary-expression
   clone   clone-expression
```

**Comment by ramsey** [comment]
Or maybe it's meant to save space by collapsing a few things, since I see `clone-expression` is also used in `exponentiation-expression`:

```
exponentiation-expression:
   clone-expression
   clone-expression   **   exponentiation-expression
```

Is it trying to express this in a more compact way?

```
clone-expression:
   clone   primary-expression

exponentiation-expression:
   primary_expression
   clone_expression
   primary_expression   **   exponentiation-expression
   clone_expression   **   exponentiation-expression
```

**Comment by nikic** [comment]
This is how operator precedence is specified.
