### ISSUE TITLE
"case-sensitive" and "case-insensitive" are easy to mix up

### ISSUE THREAD

**Issue by MasterZydra** [php/php-langspec#265]
Hi,
I am following the specification to implement a PHP lexer.
I noticed that there is a mix of the wording "not case-sensitive" and "case-insensitive".
Would it make sense to just use "not case-sensitive" so that it is more clear?
In my opinion "case-sensitive" and "case-insensitive" is easier to accidentally mix it up.

Examples:
https://github.com/php/php-langspec/blob/ca697b43031efd70b5306d29b74e1190e7eacac8/spec/09-lexical-structure.md?plain=1#L417
https://github.com/php/php-langspec/blob/ca697b43031efd70b5306d29b74e1190e7eacac8/spec/06-constants.md?plain=1#L37

**Comment by Girgias** [comment]
Using "not case-sensitive" is probably better, but note that this language spec is severely out of date and does not cover any recent changes/additions to the language.

**Comment by MasterZydra** [comment]
@Girgias But it is still the official language specification? So I would create a pull request for this change.

**Comment by Girgias** [comment]
> @Girgias But it is still the official language specification? So I would create a pull request for this change.

This language specification is, AFAIK, unmaintained.

From what I seem to remember from things I've been told, this was mainly created by Facebook to come up with some common ground for their implementation of HHVM to be compatible with PHP.

So this is probably only going to be good for parsing requirements up to PHP 7.0 maybe 7.1, and thus you won't have things like `readonly`, constructor property promotion, union/intersection/DNF types, etc.
