### ISSUE TITLE
Null-Coalescing Assignment Operator is Missing

### ISSUE THREAD

**Issue by jkellogg01** [php/php-langspec#267]
I'm in the early stages of writing a PHP parser and while I was looking through the language specification [here](https://phplang.org) I noticed that `??=`, the null-coalescing assignment operator, is absent from the specification. 

As you can see on the [RFC page](https://wiki.php.net/rfc/null_coalesce_equal_operator), a patch with a working implementation of the language change was approved to be merged in April of 2016 by a 37-4 vote. 

As far as I can tell this information would only need to be added to the sections on [operators and punctuators in the 'lexical structure' page](https://phplang.org/spec/09-lexical-structure.html#operators-and-punctuators) and [compound assignment in the 'expressions' page](https://phplang.org/spec/10-expressions.html#compound-assignment).

**Comment by MasterZydra** [comment]
Hi,
I had an issue open a while ago (#265). Also because I stepped over some things while implementing an PHP interpreter :)

One of the maintainers of the php-src repo wrote that this document is not going to be maintained anymore.

See https://github.com/php/php-langspec/issues/265#issuecomment-2094498972

**Comment by jkellogg01** [comment]
I see, thanks for the heads up!

I've been looking at the language spec [here](https://www.php.net/manual/en/langref.php) as a supplement, I assume that one is more up to date?

**Comment by MasterZydra** [comment]
I used this spec for the beginning of my implementation of the interpreter. For details I looked at php.net.

**Comment by iluuu1994** [comment]
Honestly, I would recommend learning yacc/bison and then looking at https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y for accurate information.
